#!/usr/bin/env python3
"""Parity tests between IAM v4.1 and Tatiana's roles-and-permissions workbook.

The workbook ("New OMS - Roles & Permissions.xlsx") is the source of truth for
role definitions and permission grants. It is not committed, so
`tests/workbook_model.json` — regenerated by `tools/extract_workbook.py` —
stands in for it here, and every assertion below is made against that model.

Covers:
  * Workbook parsing: the three worksheets are recognised, `x` becomes a
    grant, blank cells do not, function codes stay exact, no code is defined
    twice, no role is empty, and Notes/Descriptions never become codes.
  * Canonical registry: the application's PERMISSION_DEFINITIONS and
    CANONICAL_ROLE_DEFINITIONS reproduce the workbook exactly — the same 56
    codes and, per role, the same code set, including the two Agent roles
    whose matrix comes from `v2. Agent`.
  * User assignments: every user holds at least one role, every held role is
    a canonical workbook role, and the assignment is deterministic — the same
    user gets the same role across reloads and viewport changes.
  * Identity: every user's name, email, team, title, region, status, avatar
    and last login match the pre-migration snapshot. Only `roles` moved.
  * Effective access: the Edit User table and its breakdown modal are the
    union of the assigned roles' workbook codes, de-duplicated by code, with
    access-level summaries derived from grants rather than role names.
  * UI consistency: Users list, Edit User, Roles list, Edit Role, the Add
    User picker and the Redline gallery fixture all read the same registry.

Usage:
    pip install -r tests/requirements.txt
    python3 tests/test_workbook_parity.py
"""

import atexit
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, os.path.dirname(__file__))
from cdp_client import CDP  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC_DIR = os.path.join(REPO_ROOT, "public")
APP_JS = os.path.join(PUBLIC_DIR, "v4.1", "app.js")
GALLERY_JS = os.path.join(PUBLIC_DIR, "v4.1", "redline-gallery.js")
MODEL_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), "workbook_model.json")
IDENTITY_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), "user_identity_snapshot.json")

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    shutil.which("google-chrome"),
    shutil.which("chromium"),
    shutil.which("chromium-browser"),
]

results = []


def check(name, condition, detail=""):
    status = "PASS" if condition else "FAIL"
    results.append((status, name, detail))
    print("[%s] %s%s" % (status, name, ("  (%s)" % detail) if detail else ""))
    return condition


def free_port():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def start_static_server(port):
    proc = subprocess.Popen(
        [sys.executable, "-m", "http.server", str(port)],
        cwd=PUBLIC_DIR, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(50):
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.2):
                return proc
        except OSError:
            time.sleep(0.1)
    raise RuntimeError("static server did not start on port %d" % port)


def launch_chrome(debug_port):
    chrome_bin = next((c for c in CHROME_CANDIDATES if c and os.path.exists(c)), None)
    if not chrome_bin:
        raise RuntimeError("no Chrome/Chromium binary found")
    profile_dir = tempfile.mkdtemp(prefix="iam-workbook-parity-")
    proc = subprocess.Popen(
        [chrome_bin, "--headless=new", "--disable-gpu", "--no-sandbox",
         "--remote-debugging-port=%d" % debug_port, "--remote-allow-origins=*",
         "--user-data-dir=%s" % profile_dir, "about:blank"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    import urllib.request
    for _ in range(80):
        try:
            urllib.request.urlopen("http://127.0.0.1:%d/json" % debug_port, timeout=0.3)
            return proc, profile_dir
        except Exception:
            time.sleep(0.15)
    raise RuntimeError("Chrome did not open its debugging port")


# ── Static source parsing ─────────────────────────────────────────────────

def js_array_block(src, decl):
    i = src.index(decl)
    return src[i:src.index("\n];", i)]


def parse_registry():
    """Read PERMISSION_DEFINITIONS / CANONICAL_ROLE_DEFINITIONS out of app.js.

    Parsed from source rather than the runtime so a failure points at the
    fixture that is wrong, not at whatever the page happened to render.
    """
    src = open(APP_JS).read()
    perm_blk = js_array_block(src, "var PERMISSION_DEFINITIONS")
    perms = []
    for m in re.finditer(r'\{\s*code:\s*"([^"]+)",\s*application:\s*"([^"]*)",\s*'
                         r'resource:\s*"([^"]*)",\s*action:\s*"([^"]*)"', perm_blk):
        perms.append({"code": m.group(1), "application": m.group(2),
                      "resource": m.group(3), "action": m.group(4)})
    role_blk = js_array_block(src, "var CANONICAL_ROLE_DEFINITIONS")
    roles = []
    for m in re.finditer(r'id:\s*"([^"]+)",\s*name:\s*"([^"]+)"[\s\S]*?'
                         r'permissionCodes:\s*\[([^\]]*)\]', role_blk):
        roles.append({"id": m.group(1), "name": m.group(2),
                      "codes": re.findall(r'"([^"]+)"', m.group(3))})
    return perms, roles


def main():
    model = json.load(open(MODEL_JSON))
    wb_perms = model["permissions"]
    wb_roles = {r["name"]: sorted(r["codes"]) for r in model["roles"]}
    snapshot = json.load(open(IDENTITY_JSON))["users"]

    # ── 1. Workbook model sanity ──────────────────────────────────────────
    check("All three worksheets are recognised",
          model["_sheets"] == ["Core Planning", "v2. Agent", "Agents"], str(model["_sheets"]))
    codes = [p["code"] for p in wb_perms]
    check("No duplicate function codes in the workbook model",
          len(codes) == len(set(codes)), "%d codes" % len(codes))
    check("Every function code is a bare code, never a description",
          all(re.fullmatch(r"[a-z0-9_]+", c) for c in codes),
          str([c for c in codes if not re.fullmatch(r"[a-z0-9_]+", c)][:3]))
    check("Every permission names its application and resource",
          all(p["application"] and p["resource"] for p in wb_perms))
    check("No canonical role is empty",
          all(wb_roles[r] for r in wb_roles), str([r for r in wb_roles if not wb_roles[r]]))
    check("No role grants the same code twice",
          all(len(wb_roles[r]) == len(set(wb_roles[r])) for r in wb_roles))
    check("Blank cells did not become grants",
          all(set(wb_roles[r]) <= set(codes) for r in wb_roles) and
          any(len(wb_roles[r]) < len(codes) for r in wb_roles),
          "largest role holds %d of %d codes" % (max(len(v) for v in wb_roles.values()), len(codes)))
    check("The six canonical Core Planning roles are present",
          all(n in wb_roles for n in ["ACP Planner", "ACP Vendor Planner",
                                      "ACP Planning Specialist", "ACP Vendor Planning Specialist",
                                      "ACP Planning Manager", "ACP Viewer"]))
    check("The two canonical Agent roles come from `v2. Agent`",
          "Sales Agent User" in wb_roles and "Planning Agent User" in wb_roles)
    check("Codes restated on `v2. Agent` keep their Core Planning definition",
          all(next(p for p in wb_perms if p["code"] == c)["sheet"] == "Core Planning"
              for c in model["_restated_on_v2_agent"]),
          "%d restated" % len(model["_restated_on_v2_agent"]))

    # ── 2. Application registry parity ────────────────────────────────────
    app_perms, app_roles = parse_registry()
    app_codes = [p["code"] for p in app_perms]
    check("Registry defines exactly the workbook's permission codes",
          sorted(app_codes) == sorted(codes),
          "app-only %s / workbook-only %s" % (sorted(set(app_codes) - set(codes))[:3],
                                              sorted(set(codes) - set(app_codes))[:3]))
    check("Registry has no duplicate permission codes",
          len(app_codes) == len(set(app_codes)))
    check("Registry defines exactly the workbook's roles",
          [r["name"] for r in app_roles] == list(wb_roles.keys()),
          str([r["name"] for r in app_roles]))
    for r in app_roles:
        check("Role grants exactly its workbook codes: %s" % r["name"],
              sorted(r["codes"]) == wb_roles[r["name"]],
              "extra %s / missing %s" % (sorted(set(r["codes"]) - set(wb_roles[r["name"]]))[:3],
                                         sorted(set(wb_roles[r["name"]]) - set(r["codes"]))[:3]))
    check("Every role keeps a stable id",
          all(re.fullmatch(r"r\d{3}", r["id"]) for r in app_roles) and
          len({r["id"] for r in app_roles}) == len(app_roles))
    check("Permission actions are preserved, not flattened into a level",
          {p["action"] for p in app_perms} - {"read", "create", "update", "delete",
                                              "approve", "archive", "access"} == set(),
          str(sorted({p["action"] for p in app_perms})))
    check("Redline gallery's role fixture is a canonical workbook role",
          (re.search(r'var ROLE_FIXTURE = "([^"]+)"', open(GALLERY_JS).read()).group(1)
           in wb_roles),
          re.search(r'var ROLE_FIXTURE = "([^"]+)"', open(GALLERY_JS).read()).group(1))

    canonical_names = list(wb_roles.keys())

    # ── 3. Runtime ────────────────────────────────────────────────────────
    port, debug_port = free_port(), free_port()
    server = start_static_server(port)
    atexit.register(server.terminate)
    chrome, profile = launch_chrome(debug_port)
    atexit.register(chrome.terminate)
    atexit.register(lambda: shutil.rmtree(profile, ignore_errors=True))
    base = "http://127.0.0.1:%d" % port

    c = CDP(debug_port)
    c.send("Network.setCacheDisabled", {"cacheDisabled": True})
    c.send("Emulation.setDeviceMetricsOverride",
           {"width": 1440, "height": 1000, "deviceScaleFactor": 1, "mobile": False})
    c.navigate(base + "/v4.1/index.html", wait=2.0)

    def js(expr):
        return c.eval(expr)

    users = json.loads(js("JSON.stringify(DATA.concat(EXTERNAL_DATA_ARRAY))"))

    check("Every user holds at least one role",
          all(u["roles"] for u in users), str([u["id"] for u in users if not u["roles"]][:5]))
    off_pool = sorted({r for u in users for r in u["roles"] if r not in canonical_names})
    check("Every held role is a canonical workbook role", not off_pool, str(off_pool[:5]))
    check("No user is left in an unresolved state",
          not any(str(r).lower() in ("unresolved", "pending review", "needs approval",
                                     "unknown role", "no role")
                  for u in users for r in u["roles"]))
    check("Users with one valid role are not given extra roles",
          all(len(u["roles"]) == 1 for u in users),
          str([u["id"] for u in users if len(u["roles"]) != 1][:5]))

    # Identity: only `roles` may have moved. Every other field the record
    # carried before the migration must still hold the same value.
    drift = []
    for u in users:
        before = snapshot.get(u["id"])
        if before is None:
            drift.append((u["id"], "not in snapshot"))
            continue
        for f, was in before.items():
            if f in ("_array", "roles"):
                continue
            if u.get(f) != was:
                drift.append((u["id"], f, was, u.get(f)))
    check("User population is unchanged",
          len(users) == len(snapshot) and {u["id"] for u in users} == set(snapshot),
          "%d now vs %d before" % (len(users), len(snapshot)))
    check("No name, email, team, title, region, avatar, status or last login changed",
          not drift, str(drift[:3]))

    # Determinism: same identifier in, same role out, on every load.
    first = {u["id"]: u["roles"] for u in users}
    c.send("Emulation.setDeviceMetricsOverride",
           {"width": 390, "height": 900, "deviceScaleFactor": 1, "mobile": False})
    c.navigate(base + "/v4.1/index.html", wait=2.0)
    again = json.loads(js("JSON.stringify(DATA.concat(EXTERNAL_DATA_ARRAY).map("
                          "function(u){return {id:u.id, roles:u.roles};}))"))
    check("Assignment is identical after a reload at a different breakpoint",
          {u["id"]: u["roles"] for u in again} == first)
    c.send("Emulation.setDeviceMetricsOverride",
           {"width": 1440, "height": 1000, "deviceScaleFactor": 1, "mobile": False})
    c.navigate(base + "/v4.1/index.html", wait=2.0)
    third = json.loads(js("JSON.stringify(DATA.concat(EXTERNAL_DATA_ARRAY).map("
                          "function(u){return {id:u.id, roles:u.roles};}))"))
    check("Assignment is identical on a third, independent load",
          {u["id"]: u["roles"] for u in third} == first)
    check("The stable hash spreads users across the whole canonical pool",
          len({r for v in first.values() for r in v}) == len(canonical_names),
          str(sorted({r for v in first.values() for r in v})))

    # ── 3b. Pre-migration references still resolve ────────────────────────
    canonical_ids = [r["id"] for r in app_roles]
    resolved = json.loads(js(
        "JSON.stringify(LEGACY_ROLE_RECORDS.map(function(l){"
        "  return {id: l.id, name: l.name,"
        "          alias: LEGACY_ROLE_ALIASES[l.name] || null,"
        "          idAlias: LEGACY_ROLE_ALIASES[l.id] || null};"
        "}))"))
    check("Every pre-migration role name resolves to a canonical role",
          all(r["alias"] in canonical_ids for r in resolved),
          str([r["name"] for r in resolved if r["alias"] not in canonical_ids]))
    orphans = [r for r in resolved if r["id"] not in canonical_ids]
    check("Every pre-migration role id a canonical role did not take over resolves",
          orphans and all(r["idAlias"] in canonical_ids for r in orphans),
          str([r["id"] for r in orphans if r["idAlias"] not in canonical_ids]))
    check("An id a canonical role now owns is not shadowed by an alias",
          all(r["idAlias"] is None for r in resolved if r["id"] in canonical_ids),
          str([r["id"] for r in resolved if r["id"] in canonical_ids and r["idAlias"]]))

    # ── 4. Roles list reads the registry ──────────────────────────────────
    js("window.__parityErrors = [];"
       "window.addEventListener('error', function(e){ window.__parityErrors.push(String(e.message)); });"
       "window.addEventListener('unhandledrejection', function(e){ window.__parityErrors.push(String(e.reason)); });")
    js("Array.from(document.querySelectorAll('.tab-btn'))"
       ".find(function(b){return b.textContent.trim()==='Roles';}).click();")
    time.sleep(0.6)
    listed = json.loads(js("JSON.stringify(Array.from("
                           "document.querySelectorAll('#rpTbody .rp-role-link'))"
                           ".map(function(a){return a.textContent.trim();}))"))
    check("Roles list shows exactly the canonical roles, in registry order",
          listed == canonical_names, str(listed))

    # ── 5. Edit Role mirrors the role's grants ────────────────────────────
    probe_role = "ACP Planning Specialist"
    js("Array.from(document.querySelectorAll('#rpTbody .rp-role-link'))"
       ".find(function(a){return a.textContent.trim()===%s;}).click();" % json.dumps(probe_role))
    time.sleep(1.0)
    check("Edit Role opens with the canonical role name",
          js("document.getElementById('crRoleName').value") == probe_role)
    sections = json.loads(js("JSON.stringify(Array.from("
                             "document.querySelectorAll('.cr-app-section'))"
                             ".map(function(s){return s.getAttribute('data-app-key');}))"))
    expected_apps = {p["application"] for p in wb_perms if p["code"] in wb_roles[probe_role]}
    check("Edit Role renders one section per granted application",
          len(sections) == len(expected_apps),
          "%d sections vs %d applications (%s)" % (len(sections), len(expected_apps),
                                                   sorted(expected_apps)))
    ungranted = js("""
      (function(){
        var apps = Array.from(document.querySelectorAll('.cr-app-section'))
          .map(function(s){return s.getAttribute('data-app-key');});
        return apps.filter(function(k){
          var sec = document.querySelector('.cr-app-section[data-app-key="'+k+'"]');
          return !sec.querySelector('.cr-matrix tbody .cr-perm-check:checked');
        });
      })()""")
    check("No application section is rendered without a checked grant",
          not ungranted, str(ungranted))
    checked_count = js("document.querySelectorAll("
                       "'.cr-app-section .cr-matrix tbody .cr-perm-check:checked').length")
    check("Checked boxes across Edit Role match the role's grant count",
          checked_count == len(wb_roles[probe_role]),
          "%s checked vs %d codes" % (checked_count, len(wb_roles[probe_role])))

    # ── 6. Effective access is the union of the assigned roles' codes ─────
    js("(function(){var b=document.getElementById('crBack'); if (b) b.click();})()")
    time.sleep(0.5)
    js("Array.from(document.querySelectorAll('.tab-btn'))"
       ".find(function(b){return b.textContent.trim()==='Users';}).click();")
    time.sleep(0.4)
    row_role = js("(function(){var r=document.querySelector('#tbody tr');"
                  "return r ? r.children[3].textContent.trim() : null;})()")
    js("(function(){var a=document.querySelector('#tbody a.name-link'); if (a) a.click();})()")
    time.sleep(1.0)
    js("(function(){var b=document.getElementById('auEffViewBreakdown'); if (b) b.click();})()")
    time.sleep(0.6)
    breakdown_role = js("document.getElementById('auEffBreakdownRoleName').textContent.trim()")
    check("Users list and the effective-access breakdown agree on the role",
          row_role == breakdown_role, "%s vs %s" % (row_role, breakdown_role))
    check("The displayed role is a canonical workbook role", row_role in wb_roles, row_role)

    grants = js("""
      (function(){
        return Array.from(document.querySelectorAll('#auEffBreakdownSections .au-eff-modal-row'))
          .map(function(r){
            var cells = r.children;
            return {resource: cells[0].textContent.trim(),
                    actions: cells[1].textContent.trim()};
          });
      })()""")
    shown = sum(len([a for a in g["actions"].split(",") if a.strip()]) for g in grants)
    check("Breakdown lists one verb per granted permission code, no duplicates",
          shown == len(wb_roles[row_role]),
          "%d verbs shown vs %d codes" % (shown, len(wb_roles[row_role])))
    # The workbook files sensitive/regional access under a single "(all)"
    # resource, so the row count is compared against the registry's own
    # grouping of those codes rather than the raw workbook column.
    groups = js("JSON.stringify(Array.from(new Set(%s.map(permissionGroupForCode))))"
                % json.dumps(wb_roles[row_role]))
    check("Breakdown rows are exactly the role's granted resource groups",
          len(grants) == len(json.loads(groups)),
          "%d rows vs %d groups" % (len(grants), len(json.loads(groups))))
    js("(function(){var b=document.getElementById('auEffBreakdownClose'); if (b) b.click();})()")
    time.sleep(0.4)

    levels = js("""
      (function(){
        return Array.from(document.querySelectorAll('#auEffTbody tr')).map(function(r){
          return {app: r.children[0].textContent.trim(), level: r.children[1].textContent.trim()};
        });
      })()""")
    check("Effective-access levels use the existing three-label vocabulary",
          all(l["level"] in ("View Access", "Edit Access", "Full Access") for l in levels),
          str(sorted({l["level"] for l in levels})))
    # The summary label has to follow the grants, not the role's name: an
    # application the role can only read must never read as write access,
    # and one it can write must never read as view-only.
    display = json.loads(js("JSON.stringify(Object.keys(WB_APP_TOKEN).reduce("
                            "function(o,k){o[k]=appDisplayNameForToken(WB_APP_TOKEN[k]); return o;}, {}))"))
    action_by_code = {p["code"]: p["action"] for p in app_perms}
    writes = {display[p["application"]] for p in wb_perms
              if p["code"] in wb_roles[row_role]
              and action_by_code[p["code"]] not in ("read", "access")}
    granted = {display[p["application"]] for p in wb_perms if p["code"] in wb_roles[row_role]}
    by_app = {l["app"]: l["level"] for l in levels}
    check("Effective access lists exactly the applications the role can reach",
          set(by_app) == granted,
          "table %s vs grants %s" % (sorted(by_app), sorted(granted)))
    mislabelled = []
    for app, level in by_app.items():
        if app in writes and level == "View Access":
            mislabelled.append((app, level, "has write grants"))
        if app not in writes and level != "View Access":
            mislabelled.append((app, level, "read-only grants"))
    check("Access-level summaries follow the grants, not the role name",
          not mislabelled, str(mislabelled))

    # ── 7. Add User picker reads the same registry ────────────────────────
    options = json.loads(js("JSON.stringify(Array.from("
                            "document.querySelectorAll('#auRoleMultiMenu [role=\"option\"]'))"
                            ".map(function(o){return o.textContent.trim();}))"))
    check("Role picker offers exactly the canonical roles",
          options == canonical_names, str(options))

    check("No JavaScript errors while walking the role surfaces",
          js("JSON.stringify(window.__parityErrors)") == "[]",
          js("JSON.stringify(window.__parityErrors)"))

    c.close()
    passed = sum(1 for r in results if r[0] == "PASS")
    failed = sum(1 for r in results if r[0] == "FAIL")
    print()
    print("%d checks, %d passed, %d failed" % (len(results), passed, failed))
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
